name = "cloudflare-cookie-filter"
main = "src/index.ts"
compatibility_date = "2024-03-14"
compatibility_flags = ["nodejs_compat"]

[vars]
ORIGIN = "example.org" # Defines the origin server requests are forwarded to
COOKIE_PREFIX_FILTER = "prefix-" # If set, all cookies that do not start with this prefix are filtered out
